version: '3.9'

services:
  telegram-service:
    container_name: telegram-service
    build: .
    restart: always
    ports:
      - '8089:8089'
    depends_on:
      - postgres-telegram
    environment:
      TZ: Europe/Moscow
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-telegram:5432/hh-telegram-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      API_HOME_URL: http://home-service:8085
      API_USER_URL: http://user-service:8086
      API_DEVICE_URL: http://device-service:8087
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    networks:
      - app-network
      
  postgres-telegram:
    container_name: postgres-telegram
    image: postgres:15.4
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hh-telegram-service-db
    ports:
      - '5436:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    name: app-network