version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build: .
    restart: always
    ports:
      - '8088:8088'
    environment:
      TZ: Europe/Moscow
      API_HOME_URL: http://home-service:8085
      API_USER_URL: http://user-service:8086
      API_DEVICE_URL: http://device-service:8087
    networks:
      - app-network

networks:
  app-network:
    name: app-network