spring:
  application:
    name: home-service
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hh-home-service-db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  enabled: true
  topics:
    home-deleted:
      name: home-deleted
      partitions: 1
      replicas: 1
    room-deleted:
      name: room-deleted
      partitions: 1
      replicas: 1
    user-deleted:
      name: user-deleted
      partitions: 1
      replicas: 1

server:
  port: 8085

logging:
  config: classpath:logback.xml

schedulers:
  enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: false
