version: '3.9'

services:
  device-service:
    container_name: device-service
    build: .
    restart: always
    ports:
      - '8087:8087'
    depends_on:
      - postgres-device
    environment:
      TZ: Europe/Moscow
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-device:5432/hh-device-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      ACCESS_ID: ${ACCESS_ID}
      ACCESS_SECRET: ${ACCESS_SECRET}
    env_file:
      - .env
    networks:
      - app-network

  postgres-device:
    container_name: postgres-device
    image: postgres:15.4
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hh-device-service-db
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    name: app-network